project:
  type: website
  output-dir: docs

website:
  title: "Blog"
  site-url: https://blog.kevinsu.nl/
  description: "Capturing the Sublime in my World"
  favicon: blog.svg
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/WKSu/
      - icon: linkedin
        href: https://www.linkedin.com/in/wang-kevin-su/
      - icon: rss
        href: index.xml
format:
  html:
    theme: yeti
    css: styles.css

execute:
  freeze: auto

