---
toc: true
layout: post
description: Looking at the past year
categories:
draft: true
title: "Dear Thao, are you surprised?"
date: "2024-12-22"
---

Dear Thảo,

It has been a while since I wrote to you. I feel there is no thought untold as we talk every day, however, your birthday is a special occassion to reflect on the past year. A moment to take a step back from the day to day and look at the bigger picture. And what a beautiful picture it is. I remember celebrating your birthday last year in such a cozy way, with our homemade ramen and the tour through Rotterdam with some hot chocolate. It truly felt like Christmas magic. Does it feel long ago to you too? So much has happened since then. 

At the end of December, we both left the country with the promise we would spend New Year together. Unfortunately, your year started with your phone stolen and plans didn't go through. 2024 didn't start off great, however, in these dark times is where light becomes more important. I remember going to your place on the 1st of January and cleaning your room. Despite the circumstances, I felt so strengthened as you and I showed how good of a team we can be. 

Our next challenge came at the end of April, where our relationship moved towards a new dimension. I still remember calling you from the trains through Europe, showing you the beautiful landscapes and wishing you were there with me. I wanted you every day as I felt a piece of me was gone. Even now while I read back on your letter you wrote on the plane to Vietnam, I feel emotion rush over me. We found each other. We built a love that we are fighting for. And we shaped a future together. All of this could not have happened if you weren't an amazing partner. Sometimes I wonder, do we even realize how difficult this was because of how easy we managed to stay connected? I have seen love once described as "the euphoria of understanding and being understood, of your solitude cracking wide open." And every day I want to ask you how your day was because I never regret knowing more about you, understand you better and show myself to you. 

Then the period when I came to Vietnam. Where I met your family, where I saw the places that shaped you who you are, and enjoyed the food and culture of this beautiful country. But also where our families met for the first time with your parents and my siblings. I saw the wonders of the country but in my eyes you were the biggest beauty. I saw your resolve and strength, you passed the Dutch exam, you got a job, you planned so much, you drove me around Ho Chi Minh, you balanced me and your life. It was a beautiful moment in time together, seeing how our life could look like living together. I want that life with you. 

Then a lot has happened since then but to be honest, it feels like a blur. You started working and became this amazing expert despite the hard working culture. We got a place for ourselves. We got the paperwork so you can move here. We are talking about buying furniture and things for our place. Our online conversations have become even weirder (who knew it was possible?). But this is also the period where things become uncertain again. You have to shake up your life and start somewhat anew in the Netherlands. As you told me, this move, unlike your previous travels, feel more permanent too. You are making choices that come with a huge cost and uncertainty to you. And I cannot know how it feels. But I am so grateful for you. In the past, you have asked me if I was surprised to see how much love I have in me for you. I want to ask you that same question. Because I am so thankful we can build this life together in our own world. And I'll try to give you all the love you deserve, even when I know you deserve more love than I give.

While I am sad I cannot celebrate the day in person, I am so grateful you are surrounded by your family and those who care about you. Enjoy your 25th my love, as the past year you and I have done 1001 things we can be proud of. 

Your love,
Kevin